### ISSUE TITLE
Typhon Wallet not displaying connection

### ISSUE THREAD

**Issue by austinnegron** [TosiDrop/vm-frontend#116]
Appears that the wallet is connecting behind the scenes but is not displaying visually that the wallet is connecting in top right corner of frontend.

**Comment by reqlez** [comment]
For now, we disabled it. Maybe we should reach out to the Typhon team to ask why Eternl, Nami and Flint all work except their wallet? Maybe they are using a different standard?

**Comment by reqlez** [comment]
I talked to one of the devs from Typhon, and he explained: 

"So Typhon injects 2 connectors. 1 is ‘typhon’ which is easy to use apis

And another is ‘typhoncip30’ which is what you should be using"

We WERE NOT using typhoncip30 ...

https://docs.typhonwallet.io/
