### ISSUE TITLE
Surface transaction submit failures to user

### ISSUE THREAD

**Issue by wolf31o2** [TosiDrop/vm-frontend#129]
Freeloaderz USA load balancer has an expired SSL certificate.
![image](https://user-images.githubusercontent.com/380021/168500479-f74da058-2751-4dd7-824e-97768b6ca7e8.png)
We don't handle this well.

**Comment by aryelciu001** [comment]
how to replicate this? and where does it happen?

**Comment by wolf31o2** [comment]
I was using Eternl yesterday while the freeloaderz US load balancer was giving out an invalid SSL certificate. I suspect using any invalid custom submit API with Eternl should duplicate the issue.

**Comment by reqlez** [comment]
This was completed in 2.0.1
