### ISSUE TITLE
Page listing participating pools

### ISSUE THREAD

**Issue by wcatz** [TosiDrop/vm-frontend#132]
And what they distribute maybe, seen Here
https://vm.adaseal.eu/pools

Also a delegate now button that hooks into connected wallet.

**Comment by wolf31o2** [comment]
I've added a pass-through API call for fetching the list of pools in #142

**Comment by wolf31o2** [comment]
Let's start with just the display. A Delegate now button means generating a new type of transaction, which is significantly more work than displaying the pools.
