### ISSUE TITLE
UX issue when connecting a wallet for the first time

### ISSUE THREAD

**Issue by agaffney** [TosiDrop/vm-frontend#140]
When the dialog pops up to select the wallet to connect to and you select a wallet (such as Eternl), a new window pops up for the wallet, but when that window disappears, the page is still showing the dialog to select a wallet for a few seconds. This dialog should have some additional visual indicator (partially transparent mask, spinner, etc.) that it's waiting on the wallet to not confuse the user.

**Comment by aryelciu001** [comment]
I can't replicate this issue. My wallet connects instantly.
