### ISSUE TITLE
Reduce calls to /getsettings

### ISSUE THREAD

**Issue by wolf31o2** [TosiDrop/vm-frontend#172]
This shouldn't change often. Let's see if we can lower the number of calls significantly.

**Comment by aryelciu001** [comment]
/getsettings is only called once during claim process. Which part is calling it excessively? I might miss something

**Comment by wcatz** [comment]
After you select tokens and press claim it starts firing every second.

**Comment by aryelciu001** [comment]
found the back. will push to master
