### ISSUE TITLE
submit PR request to Cardano registry

### ISSUE THREAD

**Issue by austinnegron** [TosiDrop/vm-frontend#232]
Submit PR request to Cardano registry with TosiDrop Logo 

see previous PR here: 

https://github.com/cardano-foundation/cardano-token-registry/pull/2202/files
this has 2 problems:
1. The subject is wrong, it has a space at the end (hex character 20)
2. It doesn't have any logo

**Comment by wolf31o2** [comment]
This has been fixed.
