### ISSUE TITLE
Highlight "Tosi Team Pools" on pools page

### ISSUE THREAD

**Issue by chadle-git** [TosiDrop/vm-frontend#383]
On the *.tosidrop.io/cardano/pools page.  
We would like to highlight the pools that are included in the .env variables that are TOSIFEE_WHITELIST.
We would like for these pools to be on top and have a sentence saying something like.
"Staking with Tosi Teams Pools allows delegates for Tosi Fee free claims on this site"

The rest of the pools should have some sort of separation(not sure best way in UI) and be below the Tosi Team Pools

**Comment by reqlez** [comment]
"Staking with Tosi Teams Pools allows delegates for Tosi Fee free claims on this site"

is too long. 

Let's just start with something simple... for the title at least:

Tosi Team Pools

VM Community Pools

**Comment by reqlez** [comment]
3.0.0 release addressed this.
