### ISSUE TITLE
Add NuNet to Projects page

### ISSUE THREAD

**Issue by chadle-git** [TosiDrop/vm-frontend#392]

**Comment by chadle-git** [comment]
Can you please add NuNet to the projects page.

TOKEN: NTX
SUPPLY: 1,000,000,000

Attached are their logo's

![Image](https://user-images.githubusercontent.com/60274638/216167088-cc0fa005-dd41-462d-95a8-d46dfcb50869.png)
![Image](https://user-images.githubusercontent.com/60274638/216167089-df10e56c-4f80-4bf8-a00f-4cabcc9ad601.png)
![Image](https://user-images.githubusercontent.com/60274638/216167087-29146092-b3aa-4ce3-ad61-79d5ef1150d5.png)

Links:
Medium: https://medium.com/nunet
twitter: https://twitter.com/nunet_global
Discord: https://discord.gg/8S7JNRBHJa
telegram: https://t.me/NuNet_community

**Comment by chadle-git** [comment]
Please add this for the description.

**NuNet is a computing framework that provides globally distributed computing power for decentralized networks, by connecting the owners of data and computing resources with computational processes in demand of these resources.**

**Comment by wolf31o2** [comment]
The text goes here: `server/public/json/projects.json` and the images would be put into `server/public/img/project-logo/nunet`
