### ISSUE TITLE
Delegate now button for all active pools

### ISSUE THREAD

**Issue by wcatz** [TosiDrop/vm-frontend#394]
Let's get a delegate now button for the pools in VM. There is a lot of new users coming in from Nunet we should make it as easy as possible to delegate to VM pools. @aryelciu001 will need your expertise here.

![IMAGE 2023-02-02 04:18:23](https://user-images.githubusercontent.com/3747031/216282669-7dcf597e-6772-4f92-9c35-56907a6fae7f.jpg)

**Comment by reqlez** [comment]
New release https://github.com/TosiDrop/vm-frontend/releases/tag/v3.1.0 added this feature.
