### ISSUE TITLE
Minor UI fixes needed

### ISSUE THREAD

**Issue by reqlez** [TosiDrop/vm-frontend#47]
![image](https://user-images.githubusercontent.com/6512602/163657088-cff31c22-15c2-4f59-8573-b7a92cbbfe0f.png)

**_DONE_** 1. Space between Logo and Logo Text, possibly after logo padding was changed. Also, the Logo looks a bit too big versus Figma. Should we change UI ? or should I change the logo file ( PNG ) instead? ( what is easier / better? ) I feel the PNG has enough padding, so if it's easy to change in UI instead, might be the way to go.
2. Space between the Claim and Airdrop tabs, on mouseover shows no space... will some spacing look better?
3. Were there no icons that are supposed to show inside each button? SVG?
4. Reminder to remove https://api.qrserver.com call on page load.

![image](https://user-images.githubusercontent.com/6512602/163657187-c4ad14e1-3382-4a94-8dca-5bc851e58f70.png)

1. In Light theme, blue colour  ( #2E3192 ? ) supposed to show instead of black? Also, in Dark theme, instead of white font, #EDE2D1 should be used?  This is for the Logo "text" portion.
2. In Light theme, the background colour and top buttons do not match the colours from the Figma: https://www.figma.com/file/ljqKsNLxZcD9KGPOmwydKq/TosiDrop-UI

NOTE:  However, I do feel in the original Figma, the logo is a bit too small, too... Maybe something in between original and current is ideal?

NOTE2: Also, I just saw that the style of the buttons was supposed to be a bit different, however, if that's hard to change i'm sure people won't complain too much, but Frosty can comment on that.

**Comment by aryelciu001** [comment]
this switch is gone now, so we can close this
