### ISSUE TITLE
No rewards found for the account wording

### ISSUE THREAD

**Issue by wcatz** [TosiDrop/vm-frontend#76]
Improve upon the message when user has already claimed and no rewards available or if the user is not eligible because they are not staking to a qualified pool. List of pools to choose from and a delegate now button. Something like that. nip it at the bud and gain delegation.

![telegram-cloud-photo-size-1-5141384773585971835-x](https://user-images.githubusercontent.com/3747031/165732965-8c239ec4-957f-4907-a775-b5db99749909.jpg)

**Comment by aryelciu001** [comment]
for now we will just add ", yet."
