### ISSUE TITLE
Overflow on successful wallet claim

### ISSUE THREAD

**Issue by wcatz** [TosiDrop/vm-frontend#77]
Message is too long and overflowing modal
![image](https://user-images.githubusercontent.com/3747031/165734483-4a1e2d44-1f71-41a4-96d9-5485b042559b.png)

**Comment by wcatz** [comment]
Second transaction is processed again. VM returns minus .5 taada. This should be prevented.
![image](https://user-images.githubusercontent.com/3747031/165737812-a4464092-7a2b-4a7b-8df7-9b8b1a97f7c6.png)

**Comment by wcatz** [comment]
Would permanently printing the transaction id onto the page with a copy button help with support issues? Remove the modal altogether?

**Comment by aryelciu001** [comment]
- I have put temporary fix on the tx ID. It will still be shown, but wont overflow the box
- we need a better mechanism to get the tx status. currently it needs the wallet to check for the tx. It is better to check the unique address directly for everything (check if fee is received, check if tokens are sent)
