### ISSUE TITLE
Bug: Transaction link returned shows testnet always

### ISSUE THREAD

**Issue by wolf31o2** [TosiDrop/vm-frontend#81]
The transaction link returned shows testnet on mainnet.

![image](https://user-images.githubusercontent.com/380021/165773647-11c37d92-a0e4-4c3d-96a9-3eb619b12b6d.png)

**Comment by reqlez** [comment]
@wolf31o2   I think we removed the link all together and just show transaction ID only now, so this does not apply anymore?

**Comment by wolf31o2** [comment]
Correct.
