### ISSUE TITLE
Show insufficient funds error to user.

### ISSUE THREAD

**Issue by wcatz** [TosiDrop/vm-frontend#83]
![IMAGE 2022-04-28 10:34:40](https://user-images.githubusercontent.com/3747031/165776901-d4f5532f-d999-4815-b4f6-cccf319c6a12.jpg)

**Comment by reqlez** [comment]
@wcatz ? Can you update, otherwise we are closing the issue if you are not able to provide steps to reproduce.

**Comment by aryelciu001** [comment]
let's close this as it hasnt been reported anymore
