### ISSUE TITLE
Calculation for ADA "You'll get back (Aprox)" is incorrect

### ISSUE THREAD

**Issue by chadle-git** [TosiDrop/vm-frontend#86]
I got +7.927787 ₳ back when the interface said I would get 4.032 ₳

About 3.895787 difference on what you get back on the calculation for "You'll get back (Aprox).
In the user favor which is actually more in the end.  But might make people hesitant on paying if the cost is telling them it is almost 4 ADA.

True costs is about 
.1 ADA for VM
+
0.366009 for TX

<img width="326" alt="Capto_Capture 2022-04-28_11-15-03_AM" src="https://user-images.githubusercontent.com/60274638/165801168-c57c4e21-680d-4b83-a12a-985fa1d8a4a1.png">

<img width="1112" alt="Capto_Capture 2022-04-28_11-16-37_AM" src="https://user-images.githubusercontent.com/60274638/165801197-20cac321-62b6-4966-badb-53a09d078a2c.png">

**Comment by reqlez** [comment]
Is this in any way related to the fact that we are not using VMs API correctly? RE withdrawing "partial" versus "All" tokens? etc
