### ISSUE TITLE
Opening the app with the last enabled wallet extension disabled gives a weird error

### ISSUE THREAD

**Issue by NicSuk** [TosiDrop/vm-frontend#93]
We should improve the text to be more user friendly
![image](https://user-images.githubusercontent.com/84302571/166522918-c258c5ac-4370-4296-a0a1-1289fc0bb493.png)

**Comment by reqlez** [comment]
@NicSuk is this still an issue?

**Comment by aryelciu001** [comment]
pretty sure it isn't an issue anymore. let's close this
